### ISSUE TITLE
Disabling parallelism in test collection also disables parallelism across test collections in an assembly

### ISSUE THREAD

**Issue by gsimpson-barracuda** [D0tNet4Fun/Automation.TestFramework#41] opened 2023-09-11 19:51 UTC
In the project where myself and my team use this framework, we have multiple collections under one assembly. We would like these collections to run in parallel with each other, and have one test per parallel-capable collection running at the same time (due to some shared context issues). 

Currently, this does not seem to be possible. The solution given in the documentation for this framework is to include this attribute in the CollectionDefinition:

_[CollectionDefinition("Serial", DisableParallelization = true)]_

But this is also the setting used in the XUnit documentation for collection level parallelism (given here: https://xunit.net/docs/running-tests-in-parallel ):

_Turn off parallelism for specific Test Collection
  [CollectionDefinition(DisableParallelization = true)]
Default: false
Parallel-capable test collections will be run first (in parallel), followed by parallel-disabled test collections (run sequentially)._

So what this means for us currently, is that when we go to mark a collection to be run in sequence we remove all possible parallelization between collections at the same time, greatly increasing our execution time of these tests.

Would it be possible to separate these 2 CollectionDefinition attributes under different names so that both of these behaviors can be controlled independently?

**Comment by D0tNet4Fun** [comment] 2023-09-12 07:28
I attempted to reproduce this issue in [this test project](https://github.com/D0tNet4Fun/Automation.TestFramework/files/12583478/TestProject1.zip).

The test project defines 3 test cases, each of them belonging to a different test suite (collection). 2 of these collections are configured to run in parallel, and the 3rd one has `DisableParallelization=true`. They run as described in the xunit documentation: _parallel-capable test collections will be run first (in parallel), followed by parallel-disabled test collections (run sequentially)_.

Does this work differently for you?

**Comment by gsimpson-barracuda** [comment] 2023-09-12 19:49
This is how it works for me, but there are not enough test cases in the project to demonstrate the problem I described above. Consider a project like yours with 3 collections, A, B, and C.  Each test collection has 3 tests under them, so 9 tests in total. If Collection A and B have _DisableParallelization=true_ and C does not, this is what happens when all 3 are set to run:

1. C runs first, with all of its tests running in parallel
2. After C finishes, A and B are triggered one at a time, with the tests in A and B running sequentially

It is the behavior in step 2, the _DisableParallelization=true_ property making the collections run in sequence and their tests also run in sequence, that I think should be changed. Ideally there would be a way to run A and B in parallel with each other so that tests in A and B are run sequentially with collections A and B running in parallel. In other words, can the _DisableParallelization=true_ property be changed to 2 different properties to enable a test collection to be parallel-capable with other collections but running tests sequentially inside the collection itself?

**Comment by D0tNet4Fun** [comment] 2023-09-12 20:39
It is not clear to me if what you described works the way you want if you used xunit instead of this framework. Can you confirm if this is the case?

On the other hand, this framework is designed to automate the execution of test cases. In the scenario you mentioned, imagine that each of the 9 test cases is manually executed by a tester.
1. Test suite C runs first. The 3 tests are executed by 3 testers in parallel. The other 6 testers have to wait for this test suite to complete before they can start testing.
2. Test suites A and B start running in parallel. (this is what you want, right?) 2 testers are currently working, the other 4 have to wait for them to compete.

I think this is a problem. The test cases are supposed to be isolated so that if there are 9 testers available, then each of them can work on a test in parallel. This is also the reason why this framework runs the test cases inside a collection in parallel. If you do no expect a tester to depend on the work of another tester in real life, why would you expect this to happen in this framework?

**Comment by gsimpson-barracuda** [comment] 2023-09-12 20:55
I am fairly certain based on the XUnit documentation https://xunit.net/docs/running-tests-in-parallel section "Parallelism in Test Frameworks" that this is how it works in Xunit. I will make another test project overnight to confirm that this is the case.

As for the question about isolation, this would be beneficial to us because of shared context between test collections and shared resources that are used by all of the tests. Ideally, yes, all test cases would be completely isolated from each other but for our particular use case this is not possible due to shared context and resources.

**Comment by D0tNet4Fun** [comment] 2023-09-12 21:49
I think I understand the issue. It's not that you want to parallel-disable the collection by specifying `DisableParallelization=true` in its definition - which should work in the same way as xunit does. What you want is to opt-out of the framework behavior that ensures test cases in the same collection run in parallel. Something like this:

```[CollectionDefinition(DisableParallelization=false, Options=TestCaseExecutionOptions.RunSequentially)]```

Is this right?

**Comment by D0tNet4Fun** [comment] 2023-09-13 11:18
I added a fix for this in `1.2.0-preview.1` and pushed it to nuget.org. Take a look at the [updated documentation](https://github.com/D0tNet4Fun/Automation.TestFramework/commit/6678dca005d8a76ed0a1917d4d05ed1e413a3d6b) for instructions, and let me know how it works for you.

**Comment by gsimpson-barracuda** [comment] 2023-09-13 13:12
> I think I understand the issue. It's not that you want to parallel-disable the collection by specifying `DisableParallelization=true` in its definition - which should work in the same way as xunit does. What you want is to opt-out of the framework behavior that ensures test cases in the same collection run in parallel. Something like this:
> 
> `[CollectionDefinition(DisableParallelization=false, Options=TestCaseExecutionOptions.RunSequentially)]`
> 
> Is this right?

Yes exactly! We don't need it for every case, just the ability to choose the desired behavior when we need it. I also confirmed that this is how the default XUnit framework behavior works. My test project is attached and in there can be seen the 3 stages of test execution when I run all of them on my machine in the screenshots.

[Collection_Behavior_XUnit.zip](https://github.com/D0tNet4Fun/Automation.TestFramework/files/12597773/Collection_Behavior_XUnit.zip)

Thank you so much for your updates on this and I will test out the new version in our solution today.

**Comment by gsimpson-barracuda** [comment] 2023-09-13 13:29
Just a heads up, when I went to go update the package I had to install 2 more NuGet packages: xunit.extensibility.core (2.5.0) and xunit.extensibility.execution (2.5.0) before it would let me update to the preview version. These might be worth marking as dependencies in NuGet if they are not already.

**Comment by gsimpson-barracuda** [comment] 2023-09-13 14:16
When I run unit tests with the new package version (regardless of whether the declared collection has the new option or not) I am getting this exception after the first Input stage of a test executes:

System.InvalidOperationException
The current test step could not be determined.
   at Automation.TestFramework.TestStep.GetCurrent(String sourceFilePath)

This is happening on all of our tests that I am using to verify. The first stage (which is usually an Input stage) runs but the next one (which is usually an ExpectedResults stage) fails with this exception.

I tried updating the referenced xunit packages used by the solution, but using the latest stable release packages it seems that did not change the behavior at all.

List of xunit NuGet packages and versions:
<img width="516" alt="image" src="https://github.com/D0tNet4Fun/Automation.TestFramework/assets/111463659/bcae8a76-80e4-4511-9320-cc0cfa457cb3">

Everything is on 2.5.0

Do I need to do anything else with the NuGet packages? Can you reproduce this behavior in a project you have locally with Input and ExpectedResults steps?

**Comment by D0tNet4Fun** [comment] 2023-09-13 14:40
I added #45 which is sort of related to this. Hopefully that will fix your issue.

**Comment by gsimpson-barracuda** [comment] 2023-09-13 14:44
Thank you! Can you push this to NuGet so I can verify if this fixes the problem or not?

**Comment by D0tNet4Fun** [comment] 2023-09-13 15:41
This is now available in `1.2.0`.

**Closed by D0tNet4Fun** 2023-09-13 15:41 UTC
